# Generated by Django 5.2.4 on 2025-07-31 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_plan_alter_userplan_user_alter_userplan_plan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userplan',
            old_name='purchased_at',
            new_name='purchase_date',
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
