# Generated by Django 5.2.4 on 2025-09-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_sitesetting_remove_course_content_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_link',
            field=models.URLField(blank=True, help_text='Add the actual course learning link here', null=True),
        ),
    ]
