# Generated by Django 5.2.6 on 2025-09-17 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_course_course_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='plan',
            field=models.CharField(choices=[('NONE', 'None'), ('BASIC', 'Basic'), ('STANDARD', 'Standard'), ('ADVANCE', 'Advance'), ('PRO', 'Pro')], default='NONE', max_length=20),
        ),
    ]
