# Generated by Django 5.2.6 on 2025-09-17 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_userprofile_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.payment'),
        ),
        migrations.AddField(
            model_name='commission',
            name='percentage_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='commission',
            name='seller_plan',
            field=models.CharField(choices=[('NONE', 'None'), ('BASIC', 'Basic'), ('STANDARD', 'Standard'), ('ADVANCE', 'Advance'), ('PRO', 'Pro')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='commission',
            name='sold_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.plan'),
        ),
        migrations.CreateModel(
            name='CommissionRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_plan', models.CharField(choices=[('NONE', 'None'), ('BASIC', 'Basic'), ('STANDARD', 'Standard'), ('ADVANCE', 'Advance'), ('PRO', 'Pro')], max_length=20)),
                ('level_1_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('level_2_percentage', models.DecimalField(decimal_places=2, default=8.0, max_digits=5)),
                ('level_3_percentage', models.DecimalField(decimal_places=2, default=2.0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sold_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.plan')),
            ],
            options={
                'unique_together': {('seller_plan', 'sold_plan')},
            },
        ),
    ]
