# Generated by Django 5.2.4 on 2025-09-17 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_commission_payment_commission_percentage_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='admin_note',
            field=models.TextField(blank=True, help_text='Admin notes about commission changes', null=True),
        ),
        migrations.AddField(
            model_name='commission',
            name='is_active',
            field=models.BooleanField(default=True, help_text='False if referral chain changed'),
        ),
    ]
