# Generated by Django 5.2.4 on 2025-09-18 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_commission_admin_note_commission_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamreward',
            options={'ordering': ['order', 'referrals_required']},
        ),
        migrations.RemoveField(
            model_name='teamreward',
            name='condition',
        ),
        migrations.AddField(
            model_name='teamreward',
            name='advance_referrals_required',
            field=models.PositiveIntegerField(default=0, help_text='Minimum Advance plan referrals required'),
        ),
        migrations.AddField(
            model_name='teamreward',
            name='condition_text',
            field=models.TextField(blank=True, help_text='Display text for conditions', null=True),
        ),
        migrations.AddField(
            model_name='teamreward',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teamreward',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order'),
        ),
        migrations.AddField(
            model_name='teamreward',
            name='pro_referrals_required',
            field=models.PositiveIntegerField(default=0, help_text='Minimum Pro plan referrals required'),
        ),
        migrations.CreateModel(
            name='UserRewardAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achieved_at', models.DateTimeField(auto_now_add=True)),
                ('is_claimed', models.BooleanField(default=False)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.teamreward')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'reward')},
            },
        ),
    ]
