# Generated by Django 5.2.4 on 2025-09-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_teamreward_options_remove_teamreward_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
    ]
