# Generated by Django 5.2.4 on 2025-09-19 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_sitesetting_whatsapp_sitesetting_youtube'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetting',
            name='whatsapp',
        ),
    ]
