# Generated by Django 5.2.4 on 2025-09-19 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_sitesetting_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
