# Generated by Django 5.2.4 on 2025-09-19 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_sitesetting_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='whatsapp_channel',
            field=models.URLField(blank=True, null=True),
        ),
    ]
