# Generated by Django 5.2.7 on 2025-10-05 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_sitesetting_whatsapp_channel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesetting',
            old_name='twitter',
            new_name='tiktok',
        ),
    ]
